services:
  - type: web
    name: ba-project-tracker
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/ba-project-tracker
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
